name: CICD Pipeline for develop/feature branch

# on:
#   workflow_call:
#     inputs:
#       config-path:
#         required: false
#         type: string
#     secrets:
#       token:
#         required: false

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  #------------------------------------------------------------------------------------
  # Build Job: Installs dependencies, builds the frontend, and uploads the build artifact.
  #------------------------------------------------------------------------------------
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    outputs:
      revision: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - run: chmod +x mvnw && ./mvnw -v

      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Extract project version
        id: version
        run: |
          VERSION=$(sed -n 's/.*<version>\(.*\)<\/version>.*/\1/p' pom.xml | head -n1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with coverage
        run: |
          ./mvnw -B clean verify \
            -DskipBndBaseline=true \
            -DskipRemoteStaging=true

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            **/target/site/jacoco/jacoco.xml
            **/lcov.info

  #-----------------------------------------------------------------------------------
  # Analysis Tools: OWASP / Fossa scans  and SonarQube analysis.
  # Depends on the build job to be completed first.
  #-----------------------------------------------------------------------------------
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - run: chmod +x mvnw && ./mvnw -v
      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
 
      # - name: Build with tests
      #   run: ./mvnw -B clean verify

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v2
      #   with:
      #     args: >
      #       -Dsonar.coverage.jacoco.xmlReportPaths=coverage/**/jacoco.xml
      #   env:
      #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  

      # - name: SonarCloud Scan (Maven)
      #   run: |
      #     ./mvnw -B clean verify sonar:sonar \
      #       -Dsonar.projectKey=elenapaun000_gha-poc \
      #       -Dsonar.organization=elenapaun000 \
      #       -Dsonar.coverage.jacoco.xmlReportPaths=coverage/**/jacoco.xml \
      #       -Dsonar.coverage.exclusions=**/*test.js,**/*mock.js,**/*test.ts,**/*test.tsx,**/*mock.ts,**/*mock.tsx,icons,src/**/mocks/**/*,**/constants/**/* \
      #       -Dsonar.cpd.exclusions=**/*test.js,**/*mock.js,**/*test.ts,**/*test.tsx,**/*mock.ts,**/*mock.tsx,icons,src/**/__tests__/**/*,src/**/mocks/**/*,**/constants/**/*,**/mocks/**
      #       -Dsonar.host.url=https://sonarcloud.io
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: Build & Install
        run: ./mvnw -B clean install

      # SonarCloud via Maven (NOT github action)
      - name: SonarCloud Scan
        run: |
          ./mvnw -B
          org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
          -Dsonar.projectKey=elenapaun000_gha-poc \
          -Dsonar.organization=elenapaun000 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.coverage.exclusions=**/*test.js,**/*mock.js,**/*test.ts,**/*test.tsx,**/*mock.ts,**/*mock.tsx,icons,src/**/mocks/**/*,**/constants/**/* \
          -Dsonar.cpd.exclusions=**/*test.js,**/*mock.js,**/*test.ts,**/*test.tsx,**/*mock.ts,**/*mock.tsx,icons,src/**/__tests__/**/*,src/**/mocks/**/*,**/constants/**/*,**/mocks/** \ 
          -Dsonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependency-scan:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - run: chmod +x mvnw && ./mvnw -v
      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build and install
        run: ./mvnw -B clean install -DskipTests

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:12.2.0:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}
